# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python download

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Download file from ftp ripe 
      run: python .tools/download.py
    - name: stage changed files
      run: | 
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
    - name: Get current date
      id: date
      run: echo "TAG_NAME=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"        
    - name: commit changed files
      run: git commit -m "Auto updating alloclist.txt"  
    - name: Tag version
      run: |
        echo "tag=$TAG_NAME"
        "git tag $TAG_NAME"
    - name: push code to master
      run: git push origin
